version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: conf.py
  builder: html
  fail_on_warning: false

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf