version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - sphinx-build -b html . $READTHEDOCS_OUTPUT/html

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf