version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf

# Ajout pour indiquer la bonne branche
vcs:
  type: git
  url: https://github.com/kambioss/Documentation_GGW_LDN.git
  branch: main
