version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install -r requirements.txt
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html
      - sphinx-build -b html -d $READTHEDOCS_OUTPUT/doctrees . $READTHEDOCS_OUTPUT/html

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf