version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - echo "Building from main branch"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf