version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  jobs:
    build:
      commands:
        - sphinx-build -T -b html -d _build/doctrees . $READTHEDOCS_OUTPUT/html
        - sphinx-build -T -b latex -d _build/doctrees . $READTHEDOCS_OUTPUT/pdf

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt

formats:
  - pdf
